#trigger rebuild
---
name: keurocalc
confinement: strict
grade: stable
base: core24
adopt-info: keurocalc
apps:
  keurocalc:
    extensions:
      - kde-neon-6
    common-id: org.kde.keurocalc
    desktop: usr/share/applications/org.kde.keurocalc.desktop
    command: usr/bin/keurocalc
    plugs:
      - audio-playback
layout:
  "/usr/lib/$CRAFT_ARCH_TRIPLET/alsa-lib":
    bind: "$SNAP/usr/lib/$CRAFT_ARCH_TRIPLET/alsa-lib"
parts:
  keurocalc:
    parse-info:
      - usr/share/metainfo/org.kde.keurocalc.appdata.xml
    plugin: cmake
    source: .
    source-type: local
    cmake-parameters:
      - "-DCMAKE_INSTALL_PREFIX=/usr"
      - "-DCMAKE_BUILD_TYPE=Release"
      - "-DENABLE_TESTING=OFF"
      - "-DBUILD_TESTING=OFF"
      - "-DKDE_SKIP_TEST_SETTINGS=ON"
    prime:
      - "-usr/lib/*/cmake/*"
      - "-usr/include/*"
      - "-usr/share/ECM/*"
      - "-usr/share/doc/*"
      - "-usr/share/man/*"
      - "-usr/bin/X11"
      - "-usr/lib/gcc/$CRAFT_ARCH_TRIPLET/6.0.0"
      - "-usr/lib/aspell/*"
      - "-usr/share/lintian"
  gpu-2404:
    after: [keurocalc]
    source: https://github.com/canonical/gpu-snap.git
    plugin: dump
    override-prime: |
      craftctl default
      ${CRAFT_PART_SRC}/bin/gpu-2404-cleanup mesa-2404
    prime:
      - bin/gpu-2404-wrapper
  cleanup:
    after:
      - keurocalc
    plugin: nil
    build-snaps:
      - core24
      - kf6-core24
    override-prime: |
      set -eux
      for snap in "core24" "kf6-core24"; do
          cd "/snap/$snap/current" && find . -type f,l -exec rm -rf "${CRAFT_PRIME}/{}" \;
      done
